# Site settings
title: Bloop
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I draw pictures, play music, code websites, and write stories.
  Every now and then I even do something useful.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: losaidos
github_username:  losaidos

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null